In [1]:
import pandas as pd

df = pd.read_csv("dataset.csv")
df.head()

                                                text            label
0  The feeder line around the residential area ke...      Electricity
1  The neighborhood park at the colony entrance i...  Public Services
2  The tanker did not arrive near the market toda...            Water
3  A burst pipe near the school has left the area...            Water
4                        pani aa hi nhi rha frm mrng            Water

In [4]:
df.info()
df['label'].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    1000 non-null   object
 1   label   1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

label
Electricity        200
Public Services    200
Water              200
Roads              200
Sanitation         200
Name: count, dtype: int64

In [5]:
df.columns

Index(['text', 'label'], dtype='object')

In [6]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r"[^a-zA-Z0-9\s]", "", text)
    return text

df['text'] = df['text'].apply(clean_text)

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['label'] = le.fit_transform(df['label'])

In [8]:
def urgency_rule(text):
    urgent_keywords = ['urgent', 'immediately', 'danger', 'emergency', 'fire', 'leak']
    return int(any(word in text.lower() for word in urgent_keywords))

df['urgency'] = df['text'].apply(urgency_rule)

In [9]:
from datasets import Dataset

dataset = Dataset.from_pandas(df)
dataset = dataset.train_test_split(test_size=0.1)

In [10]:
df.head()

                                                text  label  urgency
0  the feeder line around the residential area ke...      0        0
1  the neighborhood park at the colony entrance i...      1        0
2  the tanker did not arrive near the market toda...      4        0
3  a burst pipe near the school has left the area...      4        1
4                        pani aa hi nhi rha frm mrng      4        0